const ADD_TO_CART = "ADD_TO_CART";

const INCREASE_AMOUNT = "INCREASE_AMOUNT";

const DECREASE_AMOUNT = "DECREASE_AMOUNT";

const SUM_CART_AMOUNT = "SUM_CART_AMOUNT";

export { ADD_TO_CART, INCREASE_AMOUNT, DECREASE_AMOUNT, SUM_CART_AMOUNT };
