const ADD_TO_CART = "ADD_TO_CART";

const INCREASE_AMOUNT = "INCREASE_AMOUNT";

const DECREASE_AMOUNT = "DECREASE_AMOUNT";

const SUM_CART_AMOUNT = "SUM_CART_AMOUNT";

const UPDATE_PRICE = "UPDATE_PRICE";

const DISPLAY_VALIDATION_MESSAGE = "DISPLAY_VALIDATION_MESSAGE";

const CLOSE_VALIDATION_MESSAGE = "CLOSE_VALIDATION_MESSAGE";

export {
  ADD_TO_CART,
  INCREASE_AMOUNT,
  DECREASE_AMOUNT,
  SUM_CART_AMOUNT,
  UPDATE_PRICE,
  DISPLAY_VALIDATION_MESSAGE,
  CLOSE_VALIDATION_MESSAGE,
};
